apiVersion: v1
kind: Service
metadata:
  name: knowledge-repo-server
  labels:
    app: knowledge-repo-server
spec:
  type: ClusterIP
  selector:
    app: knowledge-repo-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
